### ISSUE TITLE
How to show the name of the language in a tab?

### ISSUE THREAD

**Issue by felix91gr** [scarfacedeb/rails_admin_globalize_field#33]
Sorry for bothering you again, but how would I change the names of the locales shown in the tabs from:

`en`, `sq`, `sr`

To their names in the current locale? Something like this:

`English`, `Albanian`, `Serbian` (when in English)

`Engleski`, `Albanski`, `Srpski` (when in Serbian)

and so on?

**Comment by scarfacedeb** [comment]
@felix91gr I just released new version 1.1.0 with `Tab#label` method that you could override.

One of the ways to get what you want:
```
class RailsAdminGlobalizeField::Tab
  def label
    I18n.translate("locale_name", locale: locale)
  end
end
```

```
en:
  locale_name: "English"
de:
  locale_name: "German"
ru:
  locale_name: "Русский"
```
